theme: minima
title: Tomas Bencomo's Website
author: Tomas Bencomo
email: myemail@email.com
description: > # this means to ignore newlines until "baseurl:"
  My description here!

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
